### ISSUE TITLE
Here is some problem I found : (1)missing data  (2)same sql get error sometimes (3)the web query result is not match the console query result.

### ISSUE THREAD

**Issue by AisTop** [shunfei/indexr#10]
(1) missing data
i send 47 datas to the table auth_data5 in the night.
![image](https://cloud.githubusercontent.com/assets/13936168/21874358/86dce398-d8af-11e6-8bf9-e729432622c6.png)
but found 16  in  the moring .
![image](https://cloud.githubusercontent.com/assets/13936168/21874436/db57690c-d8af-11e6-8a83-31fe72d652fb.png)

(2)same sql get error sometimes
![image](https://cloud.githubusercontent.com/assets/13936168/21874426/d1cff5f2-d8af-11e6-8779-b90f388ae2d0.png)

(3)the web query result is not match the console query result.
the web query result is 33 
![image](https://cloud.githubusercontent.com/assets/13936168/21874458/fa398832-d8af-11e6-936e-514d4fa3da20.png)
but the console result is 16
![image](https://cloud.githubusercontent.com/assets/13936168/21874481/1358ae2e-d8b0-11e6-9929-573ba8c07053.png)

![image](https://cloud.githubusercontent.com/assets/13936168/21874477/0db18f0e-d8b0-11e6-97b0-8d1b9e3f8ed0.png)

in the   final  , i want to know  how to use the hdfs filesystem to save indexr data .
i found the data was saved in disk  ,not in the hadoop hdfs.
![image](https://cloud.githubusercontent.com/assets/13936168/21874536/6b8be994-d8b0-11e6-880c-7f6549e65bbd.png)
i also  copyed the core-site.xml  and hdfs-site.xml  to the ${drill_home}/conf   and  ${index_home}/conf .

**Comment by flowbehappy** [comment]
@AisTop 

>  i want to know how to use the hdfs filesystem to save indexr data .

IndexR will keep trying again and again to upload those segments generated by realtime ingestion, you don't need to do it yourself. 
It looks like you haven't correctly specified the `indexr.config.properties`. e.g. If your hdfs filesystem in `core-site.xml` like 
```
  <property>
    <name>fs.defaultFS</name>
    <value>hdfs://mycluster</value>
  </property>
```
Then you should specified properties in `indexr.config.properties` like:

```
indexr.fs.connection=hdfs://mycluster
indexr.fs.data.root=/indexr
```

Maybe this is the root cause to all those issues (1), (2), (3).
I will make better document for this.

And after you fix this issue, you can manually upload those segments to `hdfs://mycluster/indexr/segment/auth_data5/rt/`. And then run indexr-tool script `indexr-tool/bin/tools.sh -cmd notifysu -t auth_data5`.


About other issues:

> (1) missing data

There are some reasons may cause the row count not match event count.

* Table schema defines rollup,  i.e. `grouping` is `true`. It will merge those rows with the same dimension values.
* Events are ignored by tags not match . Check your table schema and the events' tag setting.
* Errors when parsing events. You can check if there are any errors in the drillbit.log.
* Other errors during drill queries. Check the drillbit.log.

> (2) same sql get error sometimes

The `Segment not found` errors usually cause by the segments info cache in IndexR node not match the segments on HDFD. 
Try run 
```
indexr-tool/bin/tools.sh -cmd notifysu -t auth_data5
``` 
to notify IndexR. 
You should run this script each time after you manually modify the segments on HDFS, including by Hive. Otherwise IndexR nodes will not aware of the updates.

> (3) the web query result is not match the console query result.

It may cause by errors in queries. Check `drillbit.log`.
