### ISSUE TITLE
did i miss something , still get the same  error  java.lang.NoClassDefFoundError  io.indexr.compress.bh.BhcompressLibrary

### ISSUE THREAD

**Issue by AisTop** [shunfei/indexr#9]
i run the shell 
**sh script/setup_lib.sh
sh script/setup_indexr-segment.sh
sh script/setup_indexr-query.sh**
and check it ,BhcompressLibrary.java  was  generated. and recompile the sorce .
indexr-segment-0.1.0.jar   also  has the class file 
![image](https://cloud.githubusercontent.com/assets/13936168/21842015/d80826b4-d81f-11e6-919f-4ad109fe5ad5.png)

so i  repalce the jar file  in  every node . including the indextools .
 and  restart the drill cluster.    after period  of a time , the error is found  when save in memory rows to disk.
did i miss some step ?

the error msg ==>

16:47:28.981 [IndexR-RT-Handle-4] ERROR io.indexr.segment.rt.RTSGroup - Save in memory rows to disk failed. [table: auth_data4, rtsg: rt/rtsg.201701111551.87dee7ce-877d-471c-a9f3-dc4197dcef5d.seg, segment: rts.201701111557.d1838032-d9df-4f96-bdd4-be32434e587e.seg]
java.lang.NoClassDefFoundError: Could not initialize class io.indexr.compress.bh.BhcompressLibrary
	at io.indexr.compress.bh.BHCompressor.compressInt(BHCompressor.java:68) ~[indexr-segment-0.1.0.jar:na]

**Comment by flowbehappy** [comment]
@AisTop 

` Could not initialize class io.indexr.compress.bh.BhcompressLibrary` may cause by cpp libs not correctly setting up.

Make sure you have done this:

* Deploy all boost libs in `/usr/local/lib/` to all nodes, **not** only the `libboost_system.so`
* Deploy `libbhcompress.so` to `/usr/local/lib/` in all nodes.

And it turns out that the old deployment document is misleading people. You should deploy all boost libs in `/usr/local/lib` to all nodes, not only the `libboost_system.so`. I have corrected it now. 

Really sorry for that.

**Comment by AisTop** [comment]
It's ok. think you very much.
